### ISSUE TITLE
IRM for CheXpertNoFinding generates NaN output

### ISSUE THREAD

**Issue by JunhyunB** [YyzHarry/SubpopBench#1]
After a few learning steps, the algorithm is producing NaN outputs. 

More specifically, in the file "algorithm.py" within the "_compute_loss()" function, "self.network(x)" is generating NaN values, despite the fact that neither the parameters of "self.network" nor "x" contain any NaN values.

GPU: Nvidia A100
```Environment:
	Python: 3.9.7
	PyTorch: 1.13.0+cu117
	Torchvision: 0.14.0+cu117
	CUDA: 11.7
	CUDNN: 8500
	NumPy: 1.19.5
	PIL: 9.5.0
Args:
	algorithm: IRM
	checkpoint_freq: None
	cmnist_attr_prob: 0.5
	cmnist_flip_prob: 0.25
	cmnist_label_prob: 0.5
	cmnist_spur_prob: 0.2
	data_dir: /root/data
	dataset: CheXpertNoFinding
	es_metric: min_group:accuracy
	es_patience: 5
	es_strategy: metric
	hparams: None
	hparams_seed: 0
	image_arch: resnet_sup_in1k
	output_dir: ./output/test_attrNo/CheXpertNoFinding_IRM_hparams0_seed0
	output_folder_name: test_attrNo
	pretrained: 
	resume: 
	seed: 0
	skip_model_save: False
	stage1_algo: ERM
	stage1_folder: vanilla
	steps: None
	store_name: CheXpertNoFinding_IRM_hparams0_seed0
	tb_log_all: False
	text_arch: bert-base-uncased
	train_attr: no
	use_es: False
HParams:
	batch_size: 108
	group_balanced: False
	image_arch: resnet_sup_in1k
	irm_lambda: 100.0
	irm_penalty_anneal_iters: 500
	last_layer_dropout: 0.0
	lr: 0.001
	nonlinear_classifier: False
	optimizer: sgd
	pretrained: True
	resnet18: False
	text_arch: bert-base-uncased
	weight_decay: 0.0001
Dataset:
	[train]	167093 (without attributes)
	[val]	22280
	[test]	33419
/root/anaconda3/envs/subpop/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/root/anaconda3/envs/subpop/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


step          epoch         loss          te_avg_acc    te_worst_acc  va_avg_acc    va_worst_acc 
0             0.0000        0.5206        0.9046        0.0000        0.8984        0.0000       
Traceback (most recent call last):
  File "/root/anaconda3/envs/subpop/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/subpop/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/workspace/SubpopBench/subpopbench/train.py", line 252, in <module>
    curr_metrics = {split: eval_helper.eval_metrics(algorithm, loader, device)
  File "/root/workspace/SubpopBench/subpopbench/train.py", line 252, in <dictcomp>
    curr_metrics = {split: eval_helper.eval_metrics(algorithm, loader, device)
  File "/root/workspace/SubpopBench/subpopbench/utils/eval_helper.py", line 41, in eval_metrics
    **prob_metrics(targets, preds, label_set)
  File "/root/workspace/SubpopBench/subpopbench/utils/eval_helper.py", line 128, in prob_metrics
    'AUROC_ovo': roc_auc_score(targets, preds, multi_class='ovo', labels=label_set),
  File "/root/anaconda3/envs/subpop/lib/python3.9/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/root/anaconda3/envs/subpop/lib/python3.9/site-packages/sklearn/metrics/_ranking.py", line 524, in roc_auc_score
    y_score = check_array(y_score, ensure_2d=False)
  File "/root/anaconda3/envs/subpop/lib/python3.9/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/root/anaconda3/envs/subpop/lib/python3.9/site-packages/sklearn/utils/validation.py", line 663, in check_array
    _assert_all_finite(array,
  File "/root/anaconda3/envs/subpop/lib/python3.9/site-packages/sklearn/utils/validation.py", line 103, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').```

**Comment by YyzHarry** [comment]
Hi, thanks for your interest. You could try with different `hparams_seed` for the algorithm (we used [16 hparams](https://github.com/YyzHarry/SubpopBench/blob/main/subpopbench/sweep.py#L192) for each algorithm on each dataset in the paper), as some hparams might not be good for certain algorithm/dataset/attribute. Feel free to change and experiment IRM's hparams [here](https://github.com/YyzHarry/SubpopBench/blob/main/subpopbench/hparams_registry.py#L57-L59).
